version: "3"

services:
  zex_test:
    image: zex
    restart: always
    ports:
      - "8080:8080"
    environment:
      - spring_datasource_url=jdbc:postgresql://postgres_db:5432/zex
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:latest
    container_name: PostgresCont
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zex
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
    driver: local